# Generated by Django 4.0.4 on 2022-04-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='original_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.message'),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchased_item',
            field=models.ManyToManyField(blank=True, null=True, to='backend.item'),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='customer',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='confirmation_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_r', to='backend.image'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture', to='backend.image'),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='inventory_item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='shipping_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.customershippingaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='sold_detail',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.solddetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solddetail',
            name='inventory_item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solddetail',
            name='purchased_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.customer'),
            preserve_default=False,
        ),
    ]
