# Generated by Django 4.0.4 on 2022-04-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customer_original_contact_customer_purchased_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_order', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
                ('original_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.message')),
                ('shipping_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.shippingdetail')),
                ('sold_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.solddetail')),
            ],
        ),
    ]
