# Generated by Django 4.0.4 on 2022-04-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_inventoryobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pagevisitdata',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-id']},
        ),
    ]
