# Generated by Django 4.0.4 on 2022-04-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_item_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('confirmation_r', 'Confirmation Report'), ('media', 'Other Media')], default='image', max_length=120)),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('key', models.TextField()),
                ('filetype', models.CharField(default='image/jpg', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='confirmation_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_r', to='backend.media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture', to='backend.media'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
