# Generated by Django 4.0.4 on 2022-04-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_media_alter_item_confirmation_r_alter_item_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
    ]
