# Generated by Django 4.0.4 on 2022-04-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_name_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sport_rigs', 'Sport Rigs'), ('tandem', 'Tandem'), ('student', 'Vector SE Student'), ('canopies', 'Canopies'), ('javelin_odyssey', 'Javelin-Odyssey')], default='sport_rigs', max_length=25)),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('po_number', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('confirmation_r', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_confirmation_r', to='backend.media')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='backend.name')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_picture', to='backend.media')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_size', to='backend.name')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
