# Generated by Django 4.0.4 on 2022-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_size_name_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(default='TBD', max_length=200),
        ),
    ]
