# Generated by Django 4.0.4 on 2022-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_customerhold_alter_inventoryitem_on_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('sport_rigs', 'Sport Rigs'), ('tandem', 'Tandem'), ('student', 'Vector SE Student'), ('canopies', 'Canopies'), ('javelin_odyssey', 'Javelin-Odyssey')], default='sport_rigs', max_length=25),
        ),
    ]
