# Generated by Django 4.0.4 on 2022-04-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_size_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='type',
        ),
    ]
