# Generated by Django 4.0.4 on 2022-04-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_name_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryobject',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='solddetail',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.inventoryitem'),
        ),
    ]
