# Generated by Django 4.0.4 on 2022-04-29 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_inventoryobject_inventory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_size', to='backend.size'),
        ),
    ]
